desc "Publish"
lane :publish do |options|
  publishVersion = options[:publishVersion]

  gradle(
    task: "publish",
    properties: {
        "publishVersion" => publishVersion
    }
  )
end

before_all do |lane|
  sh "export LC_ALL=en_US.UTF-8"
  sh "export LANG=en_US.UTF-8"
end